import fs from "fs";
import path from "path";
import os from "os";
import { codexSessionPath } from "./codex";

const PROJECTS_DIR = path.join(os.homedir(), ".claude", "projects");

// One prompt the human actually typed, in the order it was sent.
// Moments while working on a prompt that involved you, or threw work away.
//
// Deliberately NOT "did any tool call fail". Ordinary tool errors — a failed
// grep, a stale string in an edit, a typo in a command — are retried and fixed
// on the next call, and flagging them marks about a third of all prompts, which
// makes the signal worthless. These three are different: two of them are you,
// and the third is time lost.
export interface Friction {
  rejected: number; // you declined a tool call
  interrupted: number; // you stopped it mid-flight
  timedOut: number; // a command was killed for running too long
}

export interface Prompt {
  n: number; // 1-based position within the session
  text: string;
  ts: number;
  // Claude Code's own id for this prompt (`promptId`). Every assistant turn it
  // caused can be traced back to it, which is what per-prompt cost joins on.
  // Null for Codex, which has no equivalent.
  id: string | null;
  // Null when nothing notable happened, which is the common case.
  friction: Friction | null;
}

const MAX_TEXT = 300;
// Safety valve so one enormous session can't dominate a response.
const MAX_PER_SESSION = 500;

// Not every `type:"user"` entry is something a human typed. Claude Code injects
// plenty of machinery through the same channel — background-task reports, hook
// output, slash-command wrappers, the text of the command you ran locally.
//
// Recent transcripts label the difference outright with `promptSource`
// ("typed" vs "system"), which is what we trust. Older ones predate the field,
// and for those the tag list below is the fallback: injected content arrives
// tag-wrapped, so the leading tag gives it away.
const INJECTED_TAGS = [
  "task-notification",
  "system-reminder",
  "teammate-message",
  "command-name",
  "command-message",
  "command-args",
  "command-contents",
  "local-command-stdout",
  "local-command-stderr",
  "user-prompt-submit-hook",
  "bash-input",
  "bash-stdout",
  "bash-stderr",
  // Codex wraps its own preamble the same way
  "environment_context",
  "user_instructions",
  "permissions",
];

function isRealPrompt(text: string): boolean {
  const t = text.trim();
  if (!t) return false;
  // "[Request interrupted by user]" / "…for tool use" are transcript markers,
  // not prompts — they record that you hit escape.
  if (t.startsWith("[Request interrupted")) return false;
  if (t.startsWith("Caveat: The messages below were generated by the user")) {
    return false;
  }
  if (t.startsWith("<")) {
    const tag = t.slice(1).match(/^[a-zA-Z][\w-]*/)?.[0];
    if (tag && INJECTED_TAGS.includes(tag)) return false;
    // A whole message wrapped in one tag is machinery too, whatever it's called.
    if (tag && new RegExp(`</${tag}>\\s*$`).test(t)) return false;
  }
  return true;
}

function clean(text: string): string {
  const t = text.replace(/\s+/g, " ").trim();
  return t.length > MAX_TEXT ? t.slice(0, MAX_TEXT) + "…" : t;
}

// Transcripts are append-only, so remember how far we parsed and pick up from
// there. Only the bytes added since the last scan are ever re-read.
interface Cached {
  consumed: number; // byte offset just past the last complete line parsed
  prompts: Prompt[];
}
const cache = new Map<string, Cached>();

// `trusted` means the transcript itself vouched for this being human-typed, so
// the text heuristics are skipped — they exist only for older formats.
type LineParser = (
  entry: any
) => { text: string; ts: number; trusted: boolean; id: string | null } | null;

// Which kind of friction, if any, this line records. Transcripts are written in
// order, so an event belongs to the most recent prompt seen — no need to walk
// the parentUuid chain the way per-prompt cost does.
type FrictionParser = (entry: any) => keyof Friction | null;

function readIncremental(
  filePath: string,
  parseLine: LineParser,
  frictionOf?: FrictionParser
): Prompt[] {
  let size = 0;
  try {
    size = fs.statSync(filePath).size;
  } catch {
    return [];
  }

  let entry = cache.get(filePath);
  // File shrank — it was rotated or rewritten, so our offsets are meaningless.
  if (entry && entry.consumed > size) entry = undefined;
  if (!entry) entry = { consumed: 0, prompts: [] };
  if (size === entry.consumed) return entry.prompts;

  const start = entry.consumed;
  let text = "";
  let consumed = start;
  try {
    const len = size - start;
    const fd = fs.openSync(filePath, "r");
    const buf = Buffer.alloc(len);
    const read = fs.readSync(fd, buf, 0, len, start);
    fs.closeSync(fd);
    // Stop at the last newline: the tail may be a half-written line, and
    // cutting on a newline byte keeps multi-byte characters intact.
    const lastNl = buf.lastIndexOf(0x0a, read - 1);
    if (lastNl === -1) {
      cache.set(filePath, entry);
      return entry.prompts;
    }
    text = buf.toString("utf8", 0, lastNl + 1);
    consumed = start + lastNl + 1;
  } catch {
    return entry.prompts;
  }

  const prompts = entry.prompts;
  for (const line of text.split("\n")) {
    if (!line) continue;
    let parsed: any;
    try {
      parsed = JSON.parse(line);
    } catch {
      continue;
    }
    // Friction lands on whichever prompt is currently open. Checked before the
    // prompt parser so an event never jumps forward onto the next prompt.
    const kind = frictionOf?.(parsed);
    if (kind) {
      const open = prompts[prompts.length - 1];
      if (open) {
        open.friction ??= { rejected: 0, interrupted: 0, timedOut: 0 };
        open.friction[kind]++;
      }
      continue;
    }
    const hit = parseLine(parsed);
    if (!hit) continue;
    if (hit.trusted ? !hit.text.trim() : !isRealPrompt(hit.text)) continue;
    if (prompts.length >= MAX_PER_SESSION) break;
    prompts.push({
      n: prompts.length + 1,
      text: clean(hit.text),
      ts: hit.ts,
      id: hit.id,
      friction: null,
    });
  }

  const next = { consumed, prompts };
  cache.set(filePath, next);
  return prompts;
}

const claudeLine: LineParser = (entry) => {
  if (entry?.type !== "user" || entry.isMeta || entry.isSidechain) return null;
  // When the transcript says who wrote it, believe it: "system" covers
  // task notifications, stopped-agent notices and other injected chatter.
  const source = entry.promptSource;
  if (typeof source === "string" && source !== "typed") return null;
  const content = entry.message?.content;
  let text: string | null = null;
  if (typeof content === "string") text = content;
  else if (Array.isArray(content)) {
    // A tool result carries no typed text; a real prompt has text blocks.
    if (content.some((c: any) => c?.type === "tool_result")) return null;
    text = content
      .filter((c: any) => c?.type === "text")
      .map((c: any) => c.text ?? "")
      .join("\n");
  }
  if (!text) return null;
  return {
    text,
    ts: entry.timestamp ? Date.parse(entry.timestamp) : 0,
    trusted: source === "typed",
    id: typeof entry.promptId === "string" ? entry.promptId : null,
  };
};

// The three signals worth surfacing. Everything else a transcript calls an
// error is routine and self-corrected — see the note on `Friction`.
const claudeFriction: FrictionParser = (entry) => {
  if (entry?.toolDenialKind === "user-rejected") return "rejected";
  if (entry?.interruptedMessageId) return "interrupted";
  if (entry?.toolUseResult?.timedOutAfterMs) return "timedOut";
  return null;
};

const codexLine: LineParser = (entry) => {
  if (entry?.type !== "event_msg" || entry.payload?.type !== "user_message") {
    return null;
  }
  const text = entry.payload.message;
  if (typeof text !== "string") return null;
  // Codex has no promptSource equivalent — its rollouts wrap injected context
  // in tags, which the heuristics catch.
  return {
    text,
    ts: entry.timestamp ? Date.parse(entry.timestamp) : 0,
    trusted: false,
    id: null,
  };
};

// Codex rollouts record no equivalent of any of the three, so nothing to read.

// Is this transcript line a prompt you actually typed? Exported so the trace
// stream can number prompts using the very same test the prompt list uses —
// the two disagreeing about what counts would be worse than either being wrong,
// because the trace's "prompt 3 of 9" has to match the row you clicked.
export function typedPromptText(
  entry: any,
  provider: "claude" | "codex"
): string | null {
  const hit = (provider === "codex" ? codexLine : claudeLine)(entry);
  if (!hit) return null;
  if (hit.trusted ? !hit.text.trim() : !isRealPrompt(hit.text)) return null;
  return hit.text;
}

export function claudePrompts(project: string, sessionId: string): Prompt[] {
  return readIncremental(
    path.join(PROJECTS_DIR, project, `${sessionId}.jsonl`),
    claudeLine,
    claudeFriction
  );
}

export function codexPrompts(sessionId: string): Prompt[] {
  const file = codexSessionPath(sessionId);
  return file ? readIncremental(file, codexLine) : [];
}
